import { pgTable, uuid, varchar, text, bigint, boolean, timestamp, index } from 'drizzle-orm/pg-core';
import { delivery } from './delivery';
import { innings } from './innings';
import { match } from './match';

export const mediaTag = pgTable('media_tag', {
  id: uuid('id').primaryKey().defaultRandom(),
  deliveryId: uuid('delivery_id').references(() => delivery.id),
  inningsId: uuid('innings_id').references(() => innings.id),
  matchId: uuid('match_id').notNull().references(() => match.id),

  mediaType: varchar('media_type', { length: 20 }).notNull(),
  sourceUrl: text('source_url').notNull(),
  thumbnailUrl: text('thumbnail_url'),
  startTimestampMs: bigint('start_timestamp_ms', { mode: 'number' }),
  endTimestampMs: bigint('end_timestamp_ms', { mode: 'number' }),

  title: varchar('title', { length: 300 }),
  description: text('description'),
  tags: text('tags').array(),
  autoGenerated: boolean('auto_generated').default(false),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_media_delivery').on(table.deliveryId),
  index('idx_media_match').on(table.matchId),
]);
